version: '3'

services:
  nest-app:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app  # Mapeia o diretório atual para o diretório de trabalho do container
      - /app/node_modules  # Evita conflitos entre node_modules no host e no container
    command: npm run start:dev