# services:
#   web:
#     build: .
#     command: npm run dev
#     ports:
#       - "5173:5173"
#     develop:
#       watch:
#         - action: sync
#           path: ./
#           target: /app
#           ignore:
#             - node_modules/
#         - action: sync+restart
#           path: ./proxy/nginx.conf
#           target: /etc/nginx/conf.d/default.conf

services:
  web:
    build: .
    command: npm run dev
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
      - /app/node_modules